# Generated by Django 3.2.13 on 2022-05-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='uni',
            field=models.ManyToManyField(null=True, to='accounts.University'),
        ),
    ]
