# Generated by Django 3.2.13 on 2022-05-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
