# Generated by Django 3.2.13 on 2022-05-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_university_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
