# Generated by Django 3.2.13 on 2022-05-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_profile_pic_university_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static\\simplesocial\\images'),
        ),
    ]
