# Generated by Django 3.2.13 on 2022-05-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_university_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.University'),
        ),
    ]
