# Generated by Django 3.2.13 on 2022-05-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uni',
            field=models.ManyToManyField(to='accounts.University'),
        ),
    ]
