# Generated by Django 3.2.13 on 2022-05-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_application_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='uni',
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
        ),
    ]
